repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-added-large-files
    - id: check-yaml
- repo: https://github.com/pre-commit/pre-commit
  rev: v2.7.1
  hooks:
    - id: validate_manifest
- repo: https://github.com/anderseknert/pre-commit-opa
  rev: v1.3.0
  hooks:
  - id: opa-fmt
  - id: opa-check
    args: ['.']
  - id: opa-test
